### ISSUE TITLE
Ability to remove occurences

### ISSUE THREAD

**Issue by charbel14** [wout/chronology.js#1]
HI,

What would be the recommended way to remove/group occurrences from/within the stack?

Consider the case where you have a database and you are modifying records.. so as long as  you have not committed those modified records back to the database you would want to be able to undo /redo and once committed entries associated with the committed record should be removed from the stack. You might be working with more than one modified record at the same time.

It is almost as if you want to embed a chronology instance within an existing instance.

Thanks

**Comment by wout** [comment]
Hi, I just noticed your question.
That might be a welcome addition.

The occurences are stored in the `undos` array on the chronology instance.
But I suppose you would need to reference them with some unique key?

**Comment by charbel14** [comment]
Hi,

I would probably say group by a transaction/unique key yes? When you undo you provide the transaction key, you may have more than one transaction key at any one point in time?

Consider a canvas with multiple open forms. you commit form1 - now you clear all associated entries from the undo stack. At the same time form2 transaction is still around and  you can undo that, without any gaps in the undo stack (gaps would be where form1 entries existed prior to commit).

Also it might well be possible that you want clear partial entries of a particular transaction/unique key, for instance by type - I may have contributed an action of type input change, and form resize. On Commit I would want to say clear entries for unique key that are of type inputChange, while form resize would stay for example.

The remove occurrence can take a filter callback allowing users to define the criteria of removal..
