### ISSUE TITLE
NPM Package Issue

### ISSUE THREAD

**Issue by anolek** [wout/chronology.js#2]
Hi,

I can't install chronology.js with npm because the tag "v0.4" is not valid (not "semver compilant") :( 

Could you fix it please, by adding a new tag, like "v0.4.1" or "v0.4.0" ? :)

Thanks !

**Comment by wout** [comment]
Hi,

Thanks for using chronology!
In the meantime I tagged `v0.4.1`.

Hope that helps.

Best regards,
Wout

**Comment by Aurlin** [comment]
Hi,

Thank you for your quick reply :)
But my bad, i should mention that, the file "package.json" need to be updated too (line "version")

Could you update the file "package.json", if possible ?

Thanks again !

**Comment by wout** [comment]
I could have thought of that as ell of course. 😜
The `package.json` is now updated accordingly.

**Comment by Aurlin** [comment]
Thanks,

Working well :+1:

**Comment by wout** [comment]
Great! 😀
Enjoy!
